---
title: "Using External Simulators"
author: "Paul Staab"
date: "coala `r packageVersion('coala')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Coala-Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

Coala can call the coalescent simulators _ms_ [1], _msms_ [2] and _scrm_ [3] 
and use _seq-gen_ [4] for finite sites simulations. 

The R version of _scrm_ should get installed automatically as a dependeny of 
coala. The other three programs need to be installed manually. Short 
instructions  on obtaining and compiling the programs are given in the help 
pages of `use_ms`, `use_msms` and `use_seqgen`. 
This functions can also be used to activate the simulators from within R.

Alternatively, you can also place the programs binaries in your working
directory or in a folder listed in your _PATH_ environment variable using
one of the expected names below. If you do that, coala should be able
to automatically detect and activate the corresponding simulator when 
it is loaded via `libary(coala)`.

As a third option, you can start the R session with environment variables
that hold the path to the binaries. In this case, the simulators should
also be automatically be activated when the coala package is loaded.

| Simulator | Priority | Expected Binary Names                    | Environment Var | Function   |
| ---       | ---      | ---                                      | ---             | ---        |
| seq-gen   | 100      | seqgen, seq-gen, seqgen.exe, seq-gen.exe | SEQGEN          | use_seqgen |
| msms      | 200      | msms.jar / java, java.exe                | MSMS / JAVA     | use_msms   |
| ms        | 300      | ms, ms.exe                               | MS              | use_ms     |
| scrm      | 400      |                                          |                 |            |


In case multiple simulators can simulate a model, the one with the highest 
priority is be used. The priority values can be adapted using the 
`use_ms`, `use_msms` and `use_seqgen` commands.

Finally, you can use the `list_simulators()` command to view which 
simulators are currently available.


References
----------
* __[1]__: Richard R. Hudson. 
  _Generating samples under a Wright-Fisher neutral model of genetic variation._
  Bioinformatics (2002) 18 (2): 337-338
  [doi:10.1093/bioinformatics/18.2.337](http://doi.org/10.1093/bioinformatics/18.2.337)
* __[2]__: Gregory Ewing and Joachim Hermisson.
  _MSMS: a coalescent simulation program including recombination,
  demographic structure and selection at a single locus._
  Bioinformatics (2010) 26 (16): 2064-2065
  [doi:10.1093/bioinformatics/btq322](http://doi.org/10.1093/bioinformatics/btq322)
* __[3]__: Paul R. Staab, Sha Zhu, Dirk Metzler and Gerton Lunter. 
  _scrm: efficiently simulating long sequences using the approximated 
  coalescent with recombination._
  Bioinformatics (2015) 31 (10): 1680-1682. 
  [doi:10.1093/bioinformatics/btu861](http://doi.org/doi:10.1093/bioinformatics/btu861)
* __[4]__: Andrew Rambaut and Nicholas C. Grass.
  _Seq-Gen: an application for the Monte Carlo simulation of DNA sequence
  evolution along phylogenetic trees._
  Comput Appl Biosci (1997) 13 (3): 235-238
  [doi:10.1093/bioinformatics/13.3.235](http://doi.org/10.1093/bioinformatics/13.3.235)
