# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseMsPositions <- function(line) {
    .Call('coalsimr_parseMsPositions', PACKAGE = 'coalsimr', line)
}

parseMsOutput <- function(file_names, sample_size, loci_number) {
    .Call('coalsimr_parseMsOutput', PACKAGE = 'coalsimr', file_names, sample_size, loci_number)
}

parseSeqgenOutput <- function(file_names, sample_size, sequence_length, loci_number, outgroup_size = 1L) {
    .Call('coalsimr_parseSeqgenOutput', PACKAGE = 'coalsimr', file_names, sample_size, sequence_length, loci_number, outgroup_size)
}

parseTrees <- function(in_file, trio_opts, tempfile) {
    .Call('coalsimr_parseTrees', PACKAGE = 'coalsimr', in_file, trio_opts, tempfile)
}

#' Calculate the JSFS from a list of segregating sites statistics
#' 
#' @param seg_sites List of segregating sites
#' @param sample_size A numberic vector of size 2, giving the sample sizes
#'        of the two population for which the JSFS is calulated
#' @return The Joint Site Frequency Spectrum, as a matrix.
calcJsfs <- function(seg_sites, sample_size) {
    .Call('coalsimr_calcJsfs', PACKAGE = 'coalsimr', seg_sites, sample_size)
}

